---
- name: deploy MongoDB and configure the database
  hosts: all
  become: yes
  # roles:
  #   - ansible-role-mongodb

  tasks:
    - name: Install mongodb package
      apt: pkg=mongodb state=latest

    - name: Allow remote connections
      become: true
      lineinfile:
        dest: /etc/mongodb.conf
        regexp: "^\\s*bind_ip.*"
        line: "bind_ip: [127.0.0.1 10.0.0.4]"
        state: present

    - name: Restart mongodb service
      service: name=mongodb state=restarted
      sudo: yes
