---
- hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Install git package
      apt:
        name: git
        state: present
        update_cache: yes
      tags:
        - packages
      async: 120
      poll: 60

    - name: Install python-pip package
      apt:
        name: python-pip
        state: present
        update_cache: yes
      tags:
        - packages
      async: 120
      poll: 60

    - name: Install python3-pip package
      apt:
        name: python3-pip
        state: present
        update_cache: yes
      tags:
        - packages
      async: 120
      poll: 60

    - name: Install python-setuptools package
      apt:
        name: python-setuptools
        state: present
        update_cache: yes
      tags:
        - packages
      async: 120
      poll: 60

    - name: Upgrade pip
      pip: name=pip state=latest
      tags:
        - packages

- import_playbook: specific_playbook.yml
