---
- hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Install base packages
      apt:
        name: ['git', 'python-pip', 'python3-pip', 'python-setuptools']
        state: present
      tags:
        - packages

    - name: Upgrade pip
      pip: name=pip state=latest
      tags:
        - packages

- import_playbook: specific_playbook.yml
