require 'vagrant-azure'


Vagrant.configure("2") do |config|

  config.vm.box = "azure"
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  # Configuramos las diferentes maquinas
  config.vm.define "maquina1" do |maquina1|
    # maquina1.vm.network "public_network", ip: "192.168.0.17"
    maquina1.vm.hostname = "maquinamongo"
    # maquina1.vm.network "private_network", ip: "192.168.76.10"

    maquina1.vm.provider "azure" do |az, override|  # Parametros para AZURE
      # Variables de entorno
      az.tenant_id = ENV['AZURE_TENANT_ID']
      az.client_id = ENV['AZURE_CLIENT_ID']
      az.client_secret = ENV['AZURE_CLIENT_SECRET']
      az.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

      # Datos para la MV
      # az.vm.network "private_network", ip: "192.168.0.10" #https://www.vagrantup.com/docs/networking/private_network.html
      az.vm_image_urn = 'Canonical:UbuntuServer:16.04-LTS:latest'
      az.vm_name = 'maquinamongo'
      az.vm_size = 'Basic_A0'
      az.resource_group_name = 'resourcegrouphito5'
      az.location = 'francecentral'
      az.tcp_endpoints = 80
      az.tcp_endpoints = 27017
    end
  end

  config.vm.define "maquina2" do |maquina2|
    # maquina2.vm.network "public_network", ip: "192.168.0.19"
    # maquina2.vm.network "private_network", ip: "192.168.0.11" #https://www.vagrantup.com/docs/networking/private_network.html

    maquina2.vm.hostname = "maquinaservicio"
    maquina2.vm.provider "azure" do |az, override|  # Parametros para AZURE
    # Variables de entorno
    az.tenant_id = ENV['AZURE_TENANT_ID']
    az.client_id = ENV['AZURE_CLIENT_ID']
    az.client_secret = ENV['AZURE_CLIENT_SECRET']
    az.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

    # Datos para la MV
    # az.vm.network "private_network", ip: "192.168.0.11" #https://www.vagrantup.com/docs/networking/private_network.html
    az.vm_image_urn = 'Canonical:UbuntuServer:16.04-LTS:latest'
    az.vm_name = 'maquinaservicio'
    az.vm_size = 'Basic_A0'
    az.resource_group_name = 'resourcegrouphito5'
    az.location = 'francecentral'
    az.tcp_endpoints = 80
    end
  end

end
